version: '3'

services:
  nginx-manager:
    build: .
    container_name: nginx-manager
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Use named volumes for better persistence
      - nginx-sites-available:/etc/nginx/sites-available
      - nginx-sites-enabled:/etc/nginx/sites-enabled
      - nginx-logs:/var/log/nginx
      - letsencrypt:/etc/letsencrypt
      - .:/app
    environment:
      - TZ=UTC
    cap_add:
      - NET_ADMIN  # For network commands
      - NET_BIND_SERVICE  # For binding to ports < 1024
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  nginx-sites-available:
  nginx-sites-enabled:
  nginx-logs:
  letsencrypt:
